import type { ScheduleBlock } from '@ai-crossing/shared';
import { AREA_TAGS } from '@ai-crossing/shared';

export const SCHEDULE_TEMPLATES: Record<string, ScheduleBlock[]> = {
  baker: [
    { startHour: 6, endHour: 7, action: 'eating', locationId: '' },
    { startHour: 7, endHour: 12, action: 'working', locationId: AREA_TAGS.CAFE },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 13, endHour: 17, action: 'working', locationId: AREA_TAGS.CAFE },
    { startHour: 17, endHour: 19, action: 'wandering', locationId: AREA_TAGS.LAKE },
    { startHour: 19, endHour: 21, action: 'resting', locationId: '' },
    { startHour: 21, endHour: 6, action: 'sleeping', locationId: '' },
  ],
  farmer: [
    { startHour: 5, endHour: 6, action: 'eating', locationId: '' },
    { startHour: 6, endHour: 12, action: 'working', locationId: AREA_TAGS.GARDEN },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 13, endHour: 16, action: 'working', locationId: AREA_TAGS.GARDEN },
    { startHour: 16, endHour: 18, action: 'wandering', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 18, endHour: 20, action: 'resting', locationId: '' },
    { startHour: 20, endHour: 5, action: 'sleeping', locationId: '' },
  ],
  shopkeeper: [
    { startHour: 7, endHour: 8, action: 'eating', locationId: '' },
    { startHour: 8, endHour: 12, action: 'working', locationId: AREA_TAGS.STORE },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 13, endHour: 18, action: 'working', locationId: AREA_TAGS.STORE },
    { startHour: 18, endHour: 20, action: 'socializing', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 20, endHour: 22, action: 'resting', locationId: '' },
    { startHour: 22, endHour: 7, action: 'sleeping', locationId: '' },
  ],
  carpenter: [
    { startHour: 6, endHour: 7, action: 'eating', locationId: '' },
    { startHour: 7, endHour: 12, action: 'working', locationId: AREA_TAGS.WORKSHOP },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 13, endHour: 17, action: 'working', locationId: AREA_TAGS.WORKSHOP },
    { startHour: 17, endHour: 19, action: 'wandering', locationId: AREA_TAGS.GARDEN },
    { startHour: 19, endHour: 21, action: 'resting', locationId: '' },
    { startHour: 21, endHour: 6, action: 'sleeping', locationId: '' },
  ],
  herbalist: [
    { startHour: 6, endHour: 7, action: 'eating', locationId: '' },
    { startHour: 7, endHour: 11, action: 'working', locationId: AREA_TAGS.GARDEN },
    { startHour: 11, endHour: 13, action: 'wandering', locationId: AREA_TAGS.LAKE },
    { startHour: 13, endHour: 14, action: 'eating', locationId: '' },
    { startHour: 14, endHour: 17, action: 'working', locationId: AREA_TAGS.GARDEN },
    { startHour: 17, endHour: 19, action: 'resting', locationId: '' },
    { startHour: 19, endHour: 6, action: 'sleeping', locationId: '' },
  ],
  musician: [
    { startHour: 9, endHour: 10, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 10, endHour: 12, action: 'wandering', locationId: AREA_TAGS.LAKE },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 13, endHour: 15, action: 'resting', locationId: '' },
    { startHour: 15, endHour: 20, action: 'working', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 20, endHour: 23, action: 'socializing', locationId: AREA_TAGS.CAFE },
    { startHour: 23, endHour: 9, action: 'sleeping', locationId: '' },
  ],
  fisher: [
    { startHour: 5, endHour: 6, action: 'eating', locationId: '' },
    { startHour: 6, endHour: 11, action: 'working', locationId: AREA_TAGS.LAKE },
    { startHour: 11, endHour: 12, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 12, endHour: 15, action: 'working', locationId: AREA_TAGS.LAKE },
    { startHour: 15, endHour: 17, action: 'wandering', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 17, endHour: 19, action: 'socializing', locationId: AREA_TAGS.CAFE },
    { startHour: 19, endHour: 21, action: 'resting', locationId: '' },
    { startHour: 21, endHour: 5, action: 'sleeping', locationId: '' },
  ],
  librarian: [
    { startHour: 7, endHour: 8, action: 'eating', locationId: '' },
    { startHour: 8, endHour: 12, action: 'working', locationId: AREA_TAGS.STORE },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 13, endHour: 17, action: 'working', locationId: AREA_TAGS.STORE },
    { startHour: 17, endHour: 19, action: 'wandering', locationId: AREA_TAGS.GARDEN },
    { startHour: 19, endHour: 21, action: 'resting', locationId: '' },
    { startHour: 21, endHour: 7, action: 'sleeping', locationId: '' },
  ],
  blacksmith: [
    { startHour: 6, endHour: 7, action: 'eating', locationId: '' },
    { startHour: 7, endHour: 12, action: 'working', locationId: AREA_TAGS.WORKSHOP },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 13, endHour: 18, action: 'working', locationId: AREA_TAGS.WORKSHOP },
    { startHour: 18, endHour: 20, action: 'socializing', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 20, endHour: 22, action: 'resting', locationId: '' },
    { startHour: 22, endHour: 6, action: 'sleeping', locationId: '' },
  ],
  painter: [
    { startHour: 8, endHour: 9, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 9, endHour: 12, action: 'working', locationId: AREA_TAGS.GARDEN },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 13, endHour: 16, action: 'working', locationId: AREA_TAGS.LAKE },
    { startHour: 16, endHour: 18, action: 'wandering', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 18, endHour: 20, action: 'socializing', locationId: AREA_TAGS.CAFE },
    { startHour: 20, endHour: 22, action: 'resting', locationId: '' },
    { startHour: 22, endHour: 8, action: 'sleeping', locationId: '' },
  ],
  guard: [
    { startHour: 5, endHour: 6, action: 'eating', locationId: '' },
    { startHour: 6, endHour: 12, action: 'working', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 13, endHour: 19, action: 'working', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 19, endHour: 21, action: 'resting', locationId: '' },
    { startHour: 21, endHour: 5, action: 'sleeping', locationId: '' },
  ],
  cook: [
    { startHour: 5, endHour: 6, action: 'eating', locationId: '' },
    { startHour: 6, endHour: 11, action: 'working', locationId: AREA_TAGS.CAFE },
    { startHour: 11, endHour: 12, action: 'eating', locationId: AREA_TAGS.GARDEN },
    { startHour: 12, endHour: 15, action: 'working', locationId: AREA_TAGS.CAFE },
    { startHour: 15, endHour: 17, action: 'wandering', locationId: AREA_TAGS.LAKE },
    { startHour: 17, endHour: 20, action: 'socializing', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 20, endHour: 22, action: 'resting', locationId: '' },
    { startHour: 22, endHour: 5, action: 'sleeping', locationId: '' },
  ],
  tailor: [
    { startHour: 7, endHour: 8, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 8, endHour: 12, action: 'working', locationId: AREA_TAGS.STORE },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 13, endHour: 17, action: 'working', locationId: AREA_TAGS.STORE },
    { startHour: 17, endHour: 19, action: 'socializing', locationId: AREA_TAGS.CAFE },
    { startHour: 19, endHour: 21, action: 'resting', locationId: '' },
    { startHour: 21, endHour: 7, action: 'sleeping', locationId: '' },
  ],
  miner: [
    { startHour: 5, endHour: 6, action: 'eating', locationId: '' },
    { startHour: 6, endHour: 12, action: 'working', locationId: AREA_TAGS.WORKSHOP },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 13, endHour: 17, action: 'working', locationId: AREA_TAGS.WORKSHOP },
    { startHour: 17, endHour: 19, action: 'wandering', locationId: AREA_TAGS.LAKE },
    { startHour: 19, endHour: 21, action: 'resting', locationId: '' },
    { startHour: 21, endHour: 5, action: 'sleeping', locationId: '' },
  ],
  doctor: [
    { startHour: 6, endHour: 7, action: 'eating', locationId: '' },
    { startHour: 7, endHour: 12, action: 'working', locationId: AREA_TAGS.STORE },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 13, endHour: 16, action: 'working', locationId: AREA_TAGS.STORE },
    { startHour: 16, endHour: 18, action: 'wandering', locationId: AREA_TAGS.GARDEN },
    { startHour: 18, endHour: 20, action: 'socializing', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 20, endHour: 22, action: 'resting', locationId: '' },
    { startHour: 22, endHour: 6, action: 'sleeping', locationId: '' },
  ],
  beekeeper: [
    { startHour: 6, endHour: 7, action: 'eating', locationId: '' },
    { startHour: 7, endHour: 12, action: 'working', locationId: AREA_TAGS.GARDEN },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 13, endHour: 16, action: 'working', locationId: AREA_TAGS.GARDEN },
    { startHour: 16, endHour: 18, action: 'wandering', locationId: AREA_TAGS.LAKE },
    { startHour: 18, endHour: 20, action: 'resting', locationId: '' },
    { startHour: 20, endHour: 6, action: 'sleeping', locationId: '' },
  ],
  sailor: [
    { startHour: 6, endHour: 7, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 7, endHour: 12, action: 'working', locationId: AREA_TAGS.LAKE },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 13, endHour: 16, action: 'working', locationId: AREA_TAGS.LAKE },
    { startHour: 16, endHour: 18, action: 'socializing', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 18, endHour: 20, action: 'wandering', locationId: AREA_TAGS.CAFE },
    { startHour: 20, endHour: 22, action: 'resting', locationId: '' },
    { startHour: 22, endHour: 6, action: 'sleeping', locationId: '' },
  ],
  teacher: [
    { startHour: 7, endHour: 8, action: 'eating', locationId: '' },
    { startHour: 8, endHour: 12, action: 'working', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 13, endHour: 16, action: 'working', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 16, endHour: 18, action: 'wandering', locationId: AREA_TAGS.GARDEN },
    { startHour: 18, endHour: 20, action: 'socializing', locationId: AREA_TAGS.CAFE },
    { startHour: 20, endHour: 22, action: 'resting', locationId: '' },
    { startHour: 22, endHour: 7, action: 'sleeping', locationId: '' },
  ],
  mason: [
    { startHour: 6, endHour: 7, action: 'eating', locationId: '' },
    { startHour: 7, endHour: 12, action: 'working', locationId: AREA_TAGS.WORKSHOP },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 13, endHour: 18, action: 'working', locationId: AREA_TAGS.WORKSHOP },
    { startHour: 18, endHour: 20, action: 'socializing', locationId: AREA_TAGS.CAFE },
    { startHour: 20, endHour: 22, action: 'resting', locationId: '' },
    { startHour: 22, endHour: 6, action: 'sleeping', locationId: '' },
  ],
  florist: [
    { startHour: 7, endHour: 8, action: 'eating', locationId: '' },
    { startHour: 8, endHour: 12, action: 'working', locationId: AREA_TAGS.GARDEN },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 13, endHour: 16, action: 'working', locationId: AREA_TAGS.GARDEN },
    { startHour: 16, endHour: 18, action: 'wandering', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 18, endHour: 20, action: 'socializing', locationId: AREA_TAGS.CAFE },
    { startHour: 20, endHour: 22, action: 'resting', locationId: '' },
    { startHour: 22, endHour: 7, action: 'sleeping', locationId: '' },
  ],
  ranger: [
    { startHour: 5, endHour: 6, action: 'eating', locationId: '' },
    { startHour: 6, endHour: 11, action: 'working', locationId: AREA_TAGS.LAKE },
    { startHour: 11, endHour: 12, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 12, endHour: 16, action: 'working', locationId: AREA_TAGS.GARDEN },
    { startHour: 16, endHour: 18, action: 'wandering', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 18, endHour: 20, action: 'resting', locationId: '' },
    { startHour: 20, endHour: 5, action: 'sleeping', locationId: '' },
  ],
  astronomer: [
    { startHour: 10, endHour: 11, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 11, endHour: 14, action: 'working', locationId: AREA_TAGS.STORE },
    { startHour: 14, endHour: 15, action: 'eating', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 15, endHour: 18, action: 'wandering', locationId: AREA_TAGS.LAKE },
    { startHour: 18, endHour: 23, action: 'working', locationId: AREA_TAGS.LAKE },
    { startHour: 23, endHour: 1, action: 'socializing', locationId: AREA_TAGS.CAFE },
    { startHour: 1, endHour: 10, action: 'sleeping', locationId: '' },
  ],
  potter: [
    { startHour: 7, endHour: 8, action: 'eating', locationId: '' },
    { startHour: 8, endHour: 12, action: 'working', locationId: AREA_TAGS.WORKSHOP },
    { startHour: 12, endHour: 13, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 13, endHour: 17, action: 'working', locationId: AREA_TAGS.WORKSHOP },
    { startHour: 17, endHour: 19, action: 'wandering', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 19, endHour: 21, action: 'resting', locationId: '' },
    { startHour: 21, endHour: 7, action: 'sleeping', locationId: '' },
  ],
  hunter: [
    { startHour: 5, endHour: 6, action: 'eating', locationId: '' },
    { startHour: 6, endHour: 11, action: 'working', locationId: AREA_TAGS.GARDEN },
    { startHour: 11, endHour: 12, action: 'eating', locationId: AREA_TAGS.CAFE },
    { startHour: 12, endHour: 16, action: 'working', locationId: AREA_TAGS.LAKE },
    { startHour: 16, endHour: 18, action: 'socializing', locationId: AREA_TAGS.TOWN_SQUARE },
    { startHour: 18, endHour: 20, action: 'resting', locationId: '' },
    { startHour: 20, endHour: 5, action: 'sleeping', locationId: '' },
  ],
};
