export const STARTER_VILLAGERS = [
  {
    id: 'maple',
    name: 'Maple',
    ageBand: 'adult' as const,
    job: 'baker',
    traits: ['cheerful', 'talkative', 'early riser'],
    likes: ['baking', 'coffee', 'morning walks'],
    dislikes: ['rain', 'arguments'],
    homeId: 'home_1',
    speakingStyle: 'Warm and encouraging, uses food metaphors',
  },
  {
    id: 'jasper',
    name: 'Jasper',
    ageBand: 'adult' as const,
    job: 'farmer',
    traits: ['quiet', 'hardworking', 'nature-lover'],
    likes: ['gardening', 'sunrises', 'simplicity'],
    dislikes: ['noise', 'crowds', 'waste'],
    homeId: 'home_2',
    speakingStyle: 'Simple and honest, speaks slowly and deliberately',
  },
  {
    id: 'luna',
    name: 'Luna',
    ageBand: 'adult' as const,
    job: 'shopkeeper',
    traits: ['witty', 'curious', 'gossip-prone'],
    likes: ['stories', 'trading', 'new things'],
    dislikes: ['boredom', 'secrets kept from her'],
    homeId: 'home_3',
    speakingStyle: 'Quick-witted, always has a deal or rumor to mention',
  },
  {
    id: 'rowan',
    name: 'Rowan',
    ageBand: 'adult' as const,
    job: 'carpenter',
    traits: ['gruff', 'loyal', 'practical'],
    likes: ['woodworking', 'honesty', 'structure'],
    dislikes: ['laziness', 'dishonesty', 'frivolity'],
    homeId: 'home_4',
    speakingStyle: 'Direct and blunt, few words but each one counts',
  },
  {
    id: 'sage',
    name: 'Sage',
    ageBand: 'adult' as const,
    job: 'herbalist',
    traits: ['gentle', 'mystical', 'introverted'],
    likes: ['herbs', 'moonlight', 'quiet reflection'],
    dislikes: ['loud noises', 'rudeness'],
    homeId: 'home_5',
    speakingStyle: 'Soft and poetic, references nature and cycles',
  },
  {
    id: 'felix',
    name: 'Felix',
    ageBand: 'young' as const,
    job: 'musician',
    traits: ['playful', 'dramatic', 'night-owl'],
    likes: ['music', 'performances', 'nighttime', 'audiences'],
    dislikes: ['mornings', 'silence', 'routine'],
    homeId: 'home_3',
    speakingStyle: 'Dramatic and expressive, speaks in rhythm and melody',
  },
];
